BGDIINF_SB-1512: fixed moto dependency issue
Skip the response 0.12.1 version from 12.11.2020 which has an issue.
See https://github.com/getsentry/responses/issues/358

We had the folllowing error due to this:

```
  File "/home/ltshb/.local/share/virtualenvs/service-stac-dhB_Mi4-/lib/python3.7/site-packages/responses.py", line 680, in _on_request
    match, match_failed_reasons = self._find_match(request)
TypeError: cannot unpack non-iterable CallbackResponse object
```