PB-1279: Add test adding existing items
This should trigger an upsert but because model Item has `unique_together = (('collection', 'name'),)` we get the following error

django.db.utils.IntegrityError: duplicate key value violates unique constraint "stac_api_item_collection_id_name_78fbc154_uniq"
DETAIL:  Key (collection_id, name)=(1, item-1) already exists.

Unfortunately, bulk_create only lets you define a flat list of unique_fields, so more complex unique constraints cannot be taken into account. Probably this needs a workaround.